apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wildfly-inventory-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi