apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wildfly-inventory-db-st
spec:
  serviceName: wildfly-inventory-db-svc
  selector:
    matchLabels:
      app: wildfly-inventory-db-statefulset
  template:
    metadata:
      name: wildfly-inventory-db-pod   
      labels:
        app: wildfly-inventory-db-statefulset
    spec:
      containers:
      - name: postgres-container
        image: postgres:9.6.18-alpine
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "fubar"
          - name: POSTGRES_DB
            value: "inventory"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: wildfly-inventory-pv-claim